### ISSUE TITLE
Instructions for setting Polygon event handlers

### ISSUE THREAD

**Issue by sbsurf** [huafu/ember-google-map#27]
Hi,

The documentation is lacking on this subject. I tried figuring it out using your Markers example, but still having trouble getting it to work.

Can you please provide an example of how to get the polygons on the map to handle the _dragend_ event, for example?

**Comment by huafu** [comment]
Yes I know about the documentation, I need to create a bigger and more detailed documentation.

I am going to answer better later, now on my phone so I can't write too much.

Since it's Ember, it all depends what you want to handle on dragend, but you should better just observe the lat/lng of an item of the polygon path, the ember way. They're updated when the user moves it, as any other stuff on the map.

If you tell me why you need to listen fort event and doing it with ember observer doesn't make sense, I'll spend some time tomorrow explaining you how to do that.

**Comment by sbsurf** [comment]
So here's a quick example of the _polygons_ property returning one polygon. Maybe you can point me in the right direction, or tell me how to observe the path properly. What I've tried so far hasn't worked:

```
  polygons: function () {
    return [{
      path: [
        {lat: 46.867223, lng: -96.909477},
        {lat: 46.80569, lng: -96.852486},
        {lat: 46.797229, lng: -96.767342},
        {lat: 46.854547, lng: -96.735069},
        {lat: 46.867223, lng: -96.909477}
      ],
      isEditable: true,
      isDraggable: true,
      googleEvents: {
        dragend: function () {
          window.console.log('inside dragEnd()');
        }
      }
    }];
  }.property('locations')
```

**Comment by huafu** [comment]
First you should not define the `googleEvents` property at all.

Then if you need to handle the change of a path entry on a polygon, you probably should define the polygonsController to a controller of yours extending `google-map/polygons` controller. Then you can observe the path with `function(){}.observes('path.@each{lat,lng}')` from that controller.

**Comment by sbsurf** [comment]
Thanks. And what's the proper way to handle an even such as click or right-click?

**Comment by sbsurf** [comment]
By the way, the approach you recommended for handling the _dragend_ event doesn't seem to be working. I get:

```
Uncaught InvalidValueError: not an Array
```
 My code:

Template:
```
<div class="listings-map">
  {{google-map googleObject=view.map
    lat=centerLat
    lng=centerLng
    zoom=zoom
    polygons=polygons
    polygonController=polygonsController
  }}
</div>
```

Item Controller:
```
import Ember from 'ember';
import baseController from 'google-map/controllers/polygons';

export default baseController.extend({
  pathObserver: function () {
    window.console.log(this.get('path'));
  }.observes('path.@each{lat,lng}')
});
```

Map Controller:
```
import Ember from 'ember';
import SearchMapController from 'my/mixins/search-map-controller';

export default Ember.Controller.extend(SearchMapController, {
  polygons: function () {
    return [{
      path: [
        {lat: 46.867223, lng: -96.909477},
        {lat: 46.80569, lng: -96.852486},
        {lat: 46.797229, lng: -96.767342},
        {lat: 46.854547, lng: -96.735069},
        {lat: 46.867223, lng: -96.909477}
      ],
      isEditable: true,
      isDraggable: true
    }];
  }.property('locations')
});

```

**Comment by huafu** [comment]
The `polygonController=polygon` in your handlebars template when calling the component is wrong. It should be a static string else it'll try to grab the controller name on that property of your current controller.

Also I noticed you wrote `import baseController from 'ember-google-map/controllers/polygon';`. It is not an error and you might know it but it sounds like you think it is not a class due to lowercase. FYI `PolygonController` is a class so better to write `import BaseController from 'ember-google-map/controllers/polygon';`. **Oh, and btw, it should be relative to your app, so `from '../controllers/google-map/polygon.js'`**

For the events, you have to extend the polygon view (`import PolygonView from '../views/google-map/polygon.js';` and define+use it as you do for the controller (at `polygonViewClass`), then in the view class, define the nam of the action to trigger on click in the `googleEvents` hash, and define the action as usually in the `actions` hash of the view. You could put this in the controller, but since it's a `visual` thing, it should be in the view.

For example, to observe the path and the click on a polygon:

```js
// controllers/polygon-path.js
import GoogleMapPolylinePathController from './google-map/polyline-path'; // yes polyline and polygon path are the same ;-)

export default GoogleMapPolylinePathController.extend({
  pathObserver: function () {
    window.console.log(this.getProperties('lat', 'lng'));
  }.observes('@each.{lat,lng}')
});
```

```js
// views/polygon.js
import GoogleMapPolygonView from './google-map/polygon.js';

export default GoogleMapPolygonView.extend({
  googleEvents: { click: 'handleClick' },
  actions: {
    handleClick: function (event) {
      // do something here
    }
  }
});
```

```handlebars
{{! templates/search-map.hbs }}
{{google-map
    lat=centerLat
    lng=centerLng
    zoom=zoom
    polygons=polygons
    polygonPathController='polygon-path'
    polygonViewClass='polygon'}}
```

**Comment by sbsurf** [comment]
Thanks. I got the click to get wired up. And I'm able to delete a polygon using _destroyGooglePolyline()_.

I haven't tried the path observer, yet, but I'm sure that will also work.

Another question:

If I add a new polygon using the Draw tool, would the component automatically detect it and add it to the polygons collection? Same goes for the deletion of newly-added polygon. Would that get wired up automatically?

**Comment by huafu** [comment]
What is `destroyGooglePolyline`?

No I cannot detect that you created a new polygon/polyline/circle/whatever. If you point me on google map lib if and where I can detect that, then create a new issue as feature request and point me out to that in the lib, I'll try to find some time to add an options such as `autoDetectNewGoogleObjects` or such...

**Comment by sbsurf** [comment]
Is this the type of stuff you're talking about:

```
google.maps.event.addListener(drawingManager, 'polygoncomplete', (polygon) => {
      Ember.Logger.debug('polygoncomplete event fired');

      google.maps.event.addListener(polygon.getPath(), 'set_at', () => {
        Ember.Logger.debug('set_at event fired');
      });
      
      google.maps.event.addListener(polygon.getPath(), 'insert_at', () => {
        Ember.Logger.debug('insert_at event fired');
      });
      
      google.maps.event.addListener(polygon.getPath(), 'remove_at', () => {
        Ember.Logger.debug('remove_at event fired');
      });
    });
  }
```

If so, I can create a new issue.

**Comment by huafu** [comment]
what is the drawing manager?

**Comment by huafu** [comment]
Sounds like yes, but it is not a feature I am going to add in the very near future, I am very busy now and it does not look like an easy to implement stuff...

**Comment by sbsurf** [comment]
FYI: https://developers.google.com/maps/documentation/javascript/drawinglayer

This was the reason I had requested an ability to add libraries.

Well, whenever you are able to look into it, keep us posted. I can create an issue to keep track of any progress.

Thanks again! I appreciate your help.

**Comment by huafu** [comment]
Please create an issue with this link as well, prepend it with `[FEATURE]`

**Comment by huafu** [comment]
@sbsurf FYI I've created more robust docs on the [wiki](https://github.com/huafu/ember-google-map/wiki)
