### ISSUE TITLE
Passing model array to markers

### ISSUE THREAD

**Issue by kriskhaira** [huafu/ember-google-map#3]
How would I pass a model array from my Ember Data store to the markers value? 

For example, I have this code:

**controllers/trips/show.js**

```
export default Ember.Controller.extend({
  lat:         40.8,
  lng:         -74.5,
  zoom:        5,
  type:        'road',
  mapTypes:    MAP_TYPES,
  markers:     [
    {title: 'liftforward', lat: 41.74646, lng: -74.98427, description: 'New office'},
    {title: 'tallan', lat: 40.74646, lng: -73.98427, description: 'Old office'},
  ],
  }
});
```

**templates/trips/show.hbs**

```
{{google-map lat=lat lng=lng type=type zoom=zoom markers=markers infoWindows=infoWindows}}
```

If I'm showing the map on a trips/show template, how do I pass trip.locations to the markers value? A trip hasMany locations; and locations have the structure including lat and lng values like in the sample markers array.

**Comment by sbsurf** [comment]
I see you filed this as a bug. I wonder if you ever resolved it.

I, too, am having the issue:

    Uncaught TypeError: Cannot read property 'lat' of undefined

I also have a model returned asynchronously, via an Ember.RSVP.hash. I think that's probably the issue. All of my markers have the required properties, and actually get debug-logged to the console by the mapping component. But the map doesn't render, because of the error above.

**Comment by huafu** [comment]
Are you sure of using the latest version of this plugin? Can you provide the source of your route, component, controller and template where all this is happening?

**Comment by sbsurf** [comment]
Thanks for the reply.

The error was actually being caused in a couple different places. Every time I'd change it one place, it would still get thrown in another, obfuscating the problem.

One of the reasons it was being thrown, was because I had set up the component in my template, specifying:

     zoom=zoom

while not setting the **zoom** property until later. Maybe it would be better to follow the same logic in this case as the logic which runs (or doesn't run) when **zoom** is not specified in the component block at all. If I leave it out, the component works fine, defaulting to **zoom=5**. 

Same suggestion applies to **lat** and **lng** as well.

Either way, the problem was on my end. Thanks again!
